kodbankasi/kodbankasi/Models/ErrorViewModel.cs
using System;

namespace kodbankasi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

kodbankasi/kodbankasi/Models/Kategori.cs
namespace kodbankasi.Models
{
    public class Kategori
    {
        public int id { get; set; }


        public string name { get; set; }
    }
}

kodbankasi/kodbankasi/Models/Kod.cs
namespace kodbankasi.Models
{
    public class Kod
    {

        public int id { get; set; }

        public string name { get; set; }

        public string description { get; set; }

        public int kategoriId { get; set; }
    }
}

kodbankasi/kodbankasi/Controllers/HomeController.cs
using kodbankasi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace kodbankasi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

kodbankasi/kodbankasi/Controllers/KategoriController.cs
using kodbankasi.IServices;
using kodbankasi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace kodbankasi.Controllers
{
    public class KategoriController : Controller
    {
        private readonly IKategoriService _kategoriService;

        public KategoriController(IKategoriService kategoriService)
        {
            _kategoriService = kategoriService;
        }

        public async Task<IActionResult> Index()
        {

            var data= await _kategoriService.GetAllAsync();
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {

            var model = new Kategori();
            return View(model);
        }

         [HttpPost]
        public async Task<IActionResult> Create(Kategori kategori)
         {

            await _kategoriService.CreateAsync(kategori);
            return RedirectToAction(nameof(Index));
        }
        

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var data = await _kategoriService.GetByIdAsync(id);
            return View(data);

        }

        
         [HttpPost]
         public async Task<IActionResult> Update(Kategori kategori)
         {
            await _kategoriService.UpdateAsync(kategori);
             return RedirectToAction(nameof(Index));
         }
        



        public async Task<IActionResult> Delete(int id)
        {
          var isdeleted = await _kategoriService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

kodbankasi/kodbankasi/Controllers/KodController.cs
using kodbankasi.IServices;
using kodbankasi.Models;
using kodbankasi.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;


namespace kodbankasi.Controllers
{
    public class KodController : Controller
    {
        private readonly IKodService _kodService;
        private readonly IKategoriService _kategoriService;

        public KodController(IKodService kodService, IKategoriService kategoriService)
        {
            _kodService = kodService;
            _kategoriService = kategoriService;
        }

        public async Task<IActionResult> Index()
        {
             var data= await _kodService.GetAllKodWithKategoriNamesAsync();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var kategori = await _kategoriService.GetAllAsync();
            ViewBag.kategoriView = new SelectList(kategori, "id", "name");
            return View();
            
        }

        
         [HttpPost]
         public async Task<IActionResult> Create(Kod kod)
         {
            await _kodService.CreateAsync(kod);
            return RedirectToAction(nameof(Index));
         }
        

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var kategori = await _kategoriService.GetAllAsync();
            ViewBag.kategoriView = new SelectList(kategori, "id", "name");
            var kod = await _kodService.GetByIdAsync(id);
            return View(kod);
        }

        
         [HttpPost]
         public async Task<IActionResult> Update(Kod kod)
         {
            await _kodService.UpdateAsync(kod);
             return RedirectToAction(nameof(Index));
         }
        


        public async Task<IActionResult> Delete(int id)
        {
            await _kodService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var data = await _kodService.GetByIdWithKategoriNamesAsync(id);
            return View(data);
        }

    }
}

kodbankasi/kodbankasi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}

<div class="text-center">
    <h1 class="display-4">Kod Bankası Uygulamasına Hoş Geldiniz</h1>
    <p>Daha Fazlası için --> <a href="https://beltek.gazi.edu.tr/">Gazi Üniversitesi Ankara Büyükşehir Belediyesi Teknik Eğitim Kursları</a></p>
</div>

kodbankasi/kodbankasi/Views/Kategori/Create.cshtml
@model Kategori
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kategori Ekle</h6>
        </div>
        <div class="card-body">
            <form asp-action="Create" method="post">
                <div class="form-group">
                    <label for="exampleInputEmail1">Kategori Adı</label>
                    <input type="text" asp-for="name" class="form-control" id="exampleInputEmail1">
                </div>
                <button type="submit" class="btn btn-primary">Ekle</button>
            </form>

        </div>
    </div>
</div>

kodbankasi/kodbankasi/Views/Kategori/Index.cshtml
@model IEnumerable<Kategori>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <div class="row">
        <a asp-controller="Kategori" asp-action="Create" class="btn btn-success btn-icon-split btn-lg">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Kategori Ekle</span>
        </a>
    </div>
    </br>
    
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kategoriler</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Kategori Adı</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Kategori Adı</th>
                            <th>İşlemler</th>

                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            
                      
                        <tr>
                                
                            <td>@item.name</td>
                                <td><a asp-controller="Kategori" asp-action="Update" asp-route-id="@item.id"><i class="fas fa-pen"></i></a> | <a asp-action="Delete" asp-route-id="@item.id"><i class="fas fa-trash"></i></a></td>

                        </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

kodbankasi/kodbankasi/Views/Kategori/Update.cshtml
@model Kategori
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kategori Güncelle</h6>
        </div>
        <div class="card-body">
            <form asp-action="Update" method="post">
                <input type="hidden" asp-for="id"/>
                <div class="form-group">
                    <label for="exampleInputEmail1">Kategori Adı</label>
                    <input type="text" asp-for="name" class="form-control" id="exampleInputEmail1">
                </div>
                <button type="submit" class="btn btn-primary">Güncelle</button>
            </form>

        </div>
    </div>
</div>

kodbankasi/kodbankasi/Views/Kod/Create.cshtml
@model Kod
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kod Ekle</h6>
        </div>
        <div class="card-body">
            <form asp-action="Create" method="post"> 
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Kategori</label>
                    @Html.DropDownListFor(model => model.kategoriId,
                    ViewBag.kategoriView as SelectList,
                        "-- Lütfen Kategorinizi Seçiniz --",
                        new { @class = "form-control ",
                        @id = "kategori",
                        @placeholder = "Kategorinizi Seçiniz",
                        required = "required"})              
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Kod Başlığı</label>
                    <input asp-for="name" type="text" class="form-control" id="exampleInputEmail1">
                </div>
                <div class="form-group">
                    <label for="exampleTextarea">Kod</label>
                    <textarea asp-for="description" class="form-control" id="exampleTextarea" rows="5"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Ekle</button>
            </form>

        </div>
    </div>
</div>

kodbankasi/kodbankasi/Views/Kod/Details.cshtml
@using kodbankasi.Dto;
@model KodDto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Earnings (Annual) Card Example -->
<div class="col-xl-12 col-md-12 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
                <h1 class="text-center">@Model.Name</h1>
                <hr />
                <small> @Model.KategoriName</small>
                <br />
                <br />
            <div class="row"><h4> @Html.Raw(@Model.Description)</h4></div>
                </div>
                </div>
            </div>

kodbankasi/kodbankasi/Views/Kod/Index.cshtml
@using kodbankasi.Dto;
@model IEnumerable<KodDto>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <div class="row">
        <a asp-controller="Kod" asp-action="Create" class="btn btn-success btn-icon-split btn-lg">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text">Kod Ekle</span>
        </a>
        
    </div>
    </br>
   
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kodlar</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Başlık</th>
                            <th>Kategori Adı</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Başlık</th>
                            <th>Kategori Adı</th>
                            <th>İşlemler</th>

                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.KategoriName</td>
                                <td>
                                    <a asp-controller="Kod" asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-eye"> </i></a> |
                                    <a asp-controller="Kod" asp-action="Update" asp-route-id="@item.Id"><i class="fas fa-pen"> </i></a> |
                                    <a asp-controller="Kod" asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash"></i></a>
                                </td>

                            </tr>
                        }
                      
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

kodbankasi/kodbankasi/Views/Kod/Update.cshtml
@model Kod
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Kod Güncelle</h6>
        </div>
        <div class="card-body">
            <form asp-action="Update" method="post">
                <input type="hidden" asp-for="id"/>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Kategori</label>
                    @Html.DropDownListFor(model => model.kategoriId,
                    ViewBag.kategoriView as SelectList,
                    "-- Lütfen Kategorinizi Seçiniz --",
                    new { @class = "form-control ",
                    @id = "kategori",
                    @placeholder = "Kategorinizi Seçiniz",
                    required = "required"})
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Kod Başlığı</label>
                    <input type="text" asp-for="name" class="form-control" id="exampleInputEmail1">
                </div>
                <div class="form-group">
                    <label for="exampleTextarea">Kod</label>
                    <textarea class="form-control" asp-for="description" id="exampleTextarea" rows="5"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Güncelle</button>
            </form>
        </div>
    </div>
</div>

kodbankasi/kodbankasi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kodbankasi</title>
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
</head>

    <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">


            <li class="nav-item active">
                <a class="nav-link" asp-controller="Kategori" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Kategori</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-controller="Kod" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Kodlar</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">                

                    </ul>

                </nav>
                <!-- End of Topbar -->
                @RenderBody()

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>





    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>